#!/usr/bin/env python3
"""Sample the seal into a COLOR-ACCURATE packed point cloud.
Every point carries the true color of the pixel it came from
(32-color quantized palette). Artwork points first (full presence),
then the field (a breath quieter). 5 bytes/point: int16 x, int16 y,
uint8 palette index."""
import struct, sys, base64
from collections import defaultdict, Counter

src, dst = sys.argv[1], sys.argv[2]
ART_MAX, FIELD_MAX = 18000, 18000

data = open(src, 'rb').read()
off  = struct.unpack('<I', data[10:14])[0]
w    = struct.unpack('<i', data[18:22])[0]
hraw = struct.unpack('<i', data[22:26])[0]
h    = abs(hraw); topdown = hraw < 0
bypp = struct.unpack('<H', data[28:30])[0] // 8
row  = ((w * bypp + 3) // 4) * 4

art, field = [], []
for y in range(h):
    sy = y if topdown else (h - 1 - y)
    for x in range(w):
        i = off + sy * row + x * bypp
        b, g, r = data[i], data[i+1], data[i+2]
        if r > 235 and g > 235 and b > 235:            # vellum background
            continue
        if r > 140 and r > b + 25 and g > 90:          # bright artwork (gold, highlights)
            art.append((x, y, r, g, b))
        else:                                          # everything else the seal IS
            field.append((x, y, r, g, b))
print('artwork px:', len(art), '| field px:', len(field))

# artwork: density-equalized per cell so the outer band can't starve the center
CELL = max(8, w // 40)
cells = defaultdict(list)
for p in art: cells[(p[0]//CELL, p[1]//CELL)].append(p)
cap = 1
while sum(min(len(v), cap) for v in cells.values()) < min(ART_MAX, len(art)):
    cap += 1
art_kept = []
for v in cells.values():
    if len(v) <= cap: art_kept.extend(v)
    else:
        k = len(v) / cap
        art_kept.extend(v[int(i * k)] for i in range(cap))
if len(art_kept) > ART_MAX:
    k = len(art_kept) / ART_MAX
    art_kept = [art_kept[int(i * k)] for i in range(ART_MAX)]

if len(field) > FIELD_MAX:                             # stratified field fill
    k = len(field) / FIELD_MAX
    field = [field[int(i * k)] for i in range(FIELD_MAX)]

pts = art_kept + field

# 32-color palette: popularity of 5-bit buckets, nearest assignment
buckets = Counter((r >> 3, g >> 3, b >> 3) for _, _, r, g, b in pts)
palette = [(r << 3 | 4, g << 3 | 4, b << 3 | 4) for (r, g, b), _ in buckets.most_common(32)]
def nearest(r, g, b):
    best, bi = 1 << 30, 0
    for i, (pr, pg, pb) in enumerate(palette):
        d = (r-pr)**2 + (g-pg)**2 + (b-pb)**2
        if d < best: best, bi = d, i
    return bi

xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
cx = (max(xs) + min(xs)) / 2; cy = (max(ys) + min(ys)) / 2
half = max(max(xs) - min(xs), max(ys) - min(ys)) / 2

raw = bytearray()
for x, y, r, g, b in pts:
    raw += struct.pack('<hhB', round((x - cx) / half * 1000),
                       round((y - cy) / half * 1000), nearest(r, g, b))
b64 = base64.b64encode(bytes(raw)).decode()
pal_js = ','.join(f'{r},{g},{b}' for r, g, b in palette)

js = f"""/* Generated by scripts/generate-emblem.sh from assets/seal.svg.
   COLOR-ACCURATE cloud: {len(art_kept)} artwork + {len(field)} field points,
   each carrying its pixel's true color (32-color palette).
   5 bytes/point: int16 x, int16 y, uint8 palette index. Do not edit. */
(function () {{
  var PAL = new Uint8Array([{pal_js}]);
  var b = atob("{b64}"), n = b.length;
  var u = new Uint8Array(n);
  for (var i = 0; i < n; i++) u[i] = b.charCodeAt(i);
  var count = (n / 5) | 0;
  var pos = new Float32Array(count * 2);
  var col = new Float32Array(count * 3);
  var dv = new DataView(u.buffer);
  for (var j = 0; j < count; j++) {{
    pos[j*2]   = dv.getInt16(j*5, true) / 1000;
    pos[j*2+1] = dv.getInt16(j*5+2, true) / 1000;
    var pi = u[j*5+4] * 3;
    col[j*3]   = PAL[pi] / 255;
    col[j*3+1] = PAL[pi+1] / 255;
    col[j*3+2] = PAL[pi+2] / 255;
  }}
  window.__ALETHEIA_EMBLEM = pos;
  window.__ALETHEIA_EMBLEM_COLOR = col;
  window.__ALETHEIA_EMBLEM_ART = {len(art_kept)};
}})();
"""
open(dst, 'w').write(js)
print('kept:', len(art_kept), 'art +', len(field), 'field =', len(pts),
      '| file KB:', round(len(js) / 1024, 1))
