#!/usr/bin/env python3
"""Sample the seal's gold artwork into a packed Int16 point cloud.
Stratified (every-nth) sampling for even coverage; output is base64 of
little-endian int16 pairs at 1/1000 precision, decoded at runtime."""
import struct, sys, base64

src, dst, MAX = sys.argv[1], sys.argv[2], int(sys.argv[3])
data = open(src, 'rb').read()
off  = struct.unpack('<I', data[10:14])[0]
w    = struct.unpack('<i', data[18:22])[0]
hraw = struct.unpack('<i', data[22:26])[0]
h    = abs(hraw); topdown = hraw < 0
bypp = struct.unpack('<H', data[28:30])[0] // 8
row  = ((w * bypp + 3) // 4) * 4

pts = []
for y in range(h):
    sy = y if topdown else (h - 1 - y)
    for x in range(w):
        i = off + sy * row + x * bypp
        b, g, r = data[i], data[i+1], data[i+2]
        if r > 235 and g > 235 and b > 235:      # vellum background
            continue
        if r > 140 and r > b + 25 and g > 90:    # gold artwork
            pts.append((x, y))
print('gold pixels:', len(pts))
if len(pts) > MAX:                                # stratified: even coverage, no speckle holes
    k = len(pts) / MAX
    pts = [pts[int(i * k)] for i in range(MAX)]

xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
cx = (max(xs) + min(xs)) / 2; cy = (max(ys) + min(ys)) / 2
half = max(max(xs) - min(xs), max(ys) - min(ys)) / 2

raw = bytearray()
for x, y in pts:
    raw += struct.pack('<hh', round((x - cx) / half * 1000), round((y - cy) / half * 1000))
b64 = base64.b64encode(bytes(raw)).decode()

js = f"""/* Generated by scripts/generate-emblem.sh from assets/seal.svg — {len(pts)} points,
   packed int16 pairs (1/1000 precision), decoded below. Do not edit by hand. */
(function () {{
  var b = atob("{b64}"), n = b.length;
  var u = new Uint8Array(n);
  for (var i = 0; i < n; i++) u[i] = b.charCodeAt(i);
  var s = new Int16Array(u.buffer);
  var f = new Float32Array(s.length);
  for (var j = 0; j < s.length; j++) f[j] = s[j] / 1000;
  window.__ALETHEIA_EMBLEM = f;
}})();
"""
open(dst, 'w').write(js)
print('points kept:', len(pts), '| file KB:', round(len(js) / 1024, 1))
