#!/usr/bin/env python3
"""Sample the seal into a two-class packed point cloud:
   class 1 — gold artwork (rings, inscription, wreath, sunburst, book)
   class 0 — the navy field (the disc itself, lightly filled)
Gold is density-equalized per grid cell so the heavy outer band cannot
starve the fine center linework. Output: base64 int16 pairs (gold first,
then navy) + a split marker. 1/1000 precision, decoded at runtime."""
import struct, sys, base64
from collections import defaultdict

src, dst = sys.argv[1], sys.argv[2]
GOLD_MAX, NAVY_MAX = 20000, 8000

data = open(src, 'rb').read()
off  = struct.unpack('<I', data[10:14])[0]
w    = struct.unpack('<i', data[18:22])[0]
hraw = struct.unpack('<i', data[22:26])[0]
h    = abs(hraw); topdown = hraw < 0
bypp = struct.unpack('<H', data[28:30])[0] // 8
row  = ((w * bypp + 3) // 4) * 4

gold, navy = [], []
for y in range(h):
    sy = y if topdown else (h - 1 - y)
    for x in range(w):
        i = off + sy * row + x * bypp
        b, g, r = data[i], data[i+1], data[i+2]
        if r > 235 and g > 235 and b > 235:            # vellum background
            continue
        if r > 140 and r > b + 25 and g > 90:          # gold artwork
            gold.append((x, y))
        elif (0.299*r + 0.587*g + 0.114*b) < 130 and b >= r - 10:   # navy field
            navy.append((x, y))
print('gold pixels:', len(gold), '| navy pixels:', len(navy))

# density-equalize gold: per-cell cap so center linework keeps every pixel
CELL = max(8, w // 40)
cells = defaultdict(list)
for p in gold: cells[(p[0]//CELL, p[1]//CELL)].append(p)
cap = 1
while sum(min(len(v), cap) for v in cells.values()) < min(GOLD_MAX, len(gold)):
    cap += 1
gold_kept = []
for v in cells.values():
    if len(v) <= cap: gold_kept.extend(v)
    else:
        k = len(v) / cap
        gold_kept.extend(v[int(i * k)] for i in range(cap))
if len(gold_kept) > GOLD_MAX:
    k = len(gold_kept) / GOLD_MAX
    gold_kept = [gold_kept[int(i * k)] for i in range(GOLD_MAX)]

if len(navy) > NAVY_MAX:                               # stratified field fill
    k = len(navy) / NAVY_MAX
    navy = [navy[int(i * k)] for i in range(NAVY_MAX)]

pts = gold_kept + navy
xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
cx = (max(xs) + min(xs)) / 2; cy = (max(ys) + min(ys)) / 2
half = max(max(xs) - min(xs), max(ys) - min(ys)) / 2

raw = bytearray()
for x, y in pts:
    raw += struct.pack('<hh', round((x - cx) / half * 1000), round((y - cy) / half * 1000))
b64 = base64.b64encode(bytes(raw)).decode()

js = f"""/* Generated by scripts/generate-emblem.sh from assets/seal.svg.
   {len(gold_kept)} gold-artwork points (density-equalized) + {len(navy)} navy-field
   points, packed int16 pairs, gold first. Do not edit by hand. */
(function () {{
  var b = atob("{b64}"), n = b.length;
  var u = new Uint8Array(n);
  for (var i = 0; i < n; i++) u[i] = b.charCodeAt(i);
  var s = new Int16Array(u.buffer);
  var f = new Float32Array(s.length);
  for (var j = 0; j < s.length; j++) f[j] = s[j] / 1000;
  window.__ALETHEIA_EMBLEM = f;
  window.__ALETHEIA_EMBLEM_GOLD = {len(gold_kept)};
}})();
"""
open(dst, 'w').write(js)
print('kept: gold', len(gold_kept), '+ navy', len(navy), '=', len(pts),
      '| file KB:', round(len(js) / 1024, 1))
