#!/usr/bin/env node
/* Re-download every vendored library at the exact versions pinned in vendor.json.
   Usage: npm run vendor  (add --fonts to also refresh font files) */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(await readFile(join(root, 'vendor.json'), 'utf8'));
const withFonts = process.argv.includes('--fonts');

const lock = { note: 'Generated by scripts/vendor.mjs. Integrity record for the vendored runtime libraries: the version each file was downloaded for, and its sha256. The test suite holds the committed files to these hashes.', libraries: {}, files: {} };

async function fetchTo(url, dest) {
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 500) throw new Error(`suspiciously small download: ${url} (${buf.length}B)`);
  await mkdir(dirname(join(root, dest)), { recursive: true });
  await writeFile(join(root, dest), buf);
  lock.files[dest] = createHash('sha256').update(buf).digest('hex');
  console.log(`  ✓ ${dest}  (${(buf.length / 1024).toFixed(1)} KB)`);
}

for (const [name, lib] of Object.entries(manifest.libraries)) {
  console.log(`${name}@${lib.version}`);
  lock.libraries[name] = lib.version;
  for (const [dest, tmpl] of Object.entries(lib.files)) {
    await fetchTo(tmpl.replace('{version}', lib.version), dest);
  }
}

if (withFonts) {
  console.log('fonts');
  for (const [dest, url] of Object.entries(manifest.fonts.files)) {
    await fetchTo(url, dest);
  }
}

if (!withFonts) {
  const prev = JSON.parse(await readFile(join(root, 'vendor.lock.json'), 'utf8').catch(() => '{"files":{}}'));
  lock.files = { ...prev.files, ...lock.files };
  await writeFile(join(root, 'vendor.lock.json'), JSON.stringify(lock, null, 2) + '\n');
  console.log('wrote vendor.lock.json');
}
console.log('vendor complete — run the test suite before committing.');
